- name: Alarm Suppress based on Host or group provided
  hosts: localhost
  gather_facts: true

  collections:
    - oracle.oci

  tasks:
    - name: Suppress alarm for a specific resource
      oracle.oci.oci_monitoring_alarm_suppression:
        alarm_id: "ocid1.alarm.oc1.iad.aaaaaaaa3mcvlki47umb7kc4pjjuy5iogp4cqjjxhnog3t75ak3joy4dovwa"
        alarm_suppression_target:
          target_type: "ALARM"
          alarm_id: "ocid1.alarm.oc1.iad.aaaaaaaa3mcvlki47umb7kc4pjjuy5iogp4cqjjxhnog3t75ak3joy4dovwa"
        display_name: "Example Suppression"
        dimensions:
          resourceId: "ocid1.instance.oc1.iad.anuwcljt6rfcedyctsspgu4ahmsd2sfrn3vdmvttrx635sfjlyjst4fsez3q"
        time_suppress_from: "2025-03-04T01:00:00.000Z"
        time_suppress_until: "2025-03-05T01:20:00.000Z"

    - name: Create alarm_suppression
      oci_monitoring_alarm_suppression:
        alarm_id: "ocid1.alarm.oc1.iad.aaaaaaaa3mcvlki47umb7kc4pjjuy5iogp4cqjjxhnog3t75ak3joy4dovwa"
        alarm_suppression_target:
          target_type: "ALARM"
          alarm_id: "ocid1.alarm.oc1.iad.aaaaaaaa3mcvlki47umb7kc4pjjuy5iogp4cqjjxhnog3t75ak3joy4dovwa"
        display_name: "display_name_example"
        dimensions:
          resourceId: "ocid1.instance.oc1.iad.anuwcljt6rfcedyctsspgu4ahmsd2sfrn3vdmvttrx635sfjlyjst4fsez3q"
        time_suppress_from: "2025-02-29T01:00:00.000Z"
        time_suppress_until: "2025-03-29T01:00:00.000Z"
#        description: "garbage"